### ISSUE TITLE
Make filetypes with auto-syncing customizable

### ISSUE THREAD

**Issue by anzic0** [jannis-baum/vivify.vim#1]
Hi,

first of all thanks for the plugin, I really like functionality and the lightweight and structured way all of vivify is written.

However, it unfortunately seems to be incompatible with the [vimwiki plugin](https://github.com/vimwiki/vimwiki). Whenever I activate it (using vims native plugin manager), the synchronisation ceases to work. After disabling vimwiki's autocommands using `:au! vimwiki` and reloading the buffer using `:e`, synchronisation automatically resumes.

Do you by any chance know why this could be?

All the best.

**Comment by jannis-baum** [comment]
Hey there! I'm happy to hear you like Vivify :)

Can you provide some more instructions for how to reproduce the issue? If I edit a markdown file and then run `packadd vimwiki`, Vivify's synchronization still works for me.

**Comment by jannis-baum** [comment]
Oh, of course, that makes sense! Vimwiki breaks the `filetype`: once you have Vimwiki loaded, it will set the `filetype` of Markdown files to `vimwiki`, i.e. Vim doesn't know anymore that it is a Markdown file. You can check this with `:set ft?`.

I can imagine that this breaks other things/plugins as well, so it might be something they should fix.

That being said, the reason I don't use `*.md` as you suggested but rather check the `filetype` is that there are [other file extensions for markdown files](https://superuser.com/a/285878), and using `*.md` works only with `.md`, while Vim's `filetype` is much more versatile, increasing compatibility.

---

My best idea for fixing this would be to introduce an option to vivify.vim that allows users to customize which filetypes should sync, by checking if the `&filetype` is in that list in the autocommand's condition.

In your case you could just add `vimwiki` then. If you want to implement this, a PR is very welcome; otherwise I'll do it at some point when I find the time :)

**Comment by anzic0** [comment]
Great!

I don't have a lot of experience with vimscript yet, but I will definitely try to implement your solution and send a pull request when I find the time :)

**Comment by anzic0** [comment]
I opened a pull request which should close this issue :) Details can be found in the commit messages.

In short, the issue is closed in two ways. One can set either of
- `let g:vivify_filetypes = ['vimwiki']`
- `let g:vimwiki_filetypes = ['markdown']`

to ensure compatibility between vivify.vim and vimwiki.

Unfortunately I can't seem to link the pull request to this issue, but apart from this, everything is set.

**Comment by jannis-baum** [comment]
Thanks!

**Comment by anzic0** [comment]
My pleasure!
